### ISSUE TITLE
Mixins for CSS3 properties

### ISSUE THREAD

**Issue by joaostein** [alexanderGugel/papier#2]
It appears that the framework aims to support old browsers as it states in the readme file.  Have you considered abstracting all CSS3 properties to mixins so you can dynamically add browser vendors when necessary and have a broader support?

Something that would help is using any CSS3 generator (http://css3generator.com/ for example) in combination of http://caniuse.com/ to create specific mixins for the properties.  Any thoughts on this?

**Comment by alexanderGugel** [comment]
There shouldn't be a need to manually add vendor prefexis since myth is being used as a post processor (see npm build script).

**Comment by joaostein** [comment]
My bad, just looked at the .styl files! By the way, awesome initiative! keep going :)
