### ISSUE TITLE
[Typo]col-6

### ISSUE THREAD

**Issue by zhouzhuojie** [alexanderGugel/papier#3]
https://github.com/alexanderGugel/papier/blob/master/index.html#L128

`<div class="col-6 bg-deep-orange"><strong>col-1</strong><br> bg-deep-orange</div>`
=>
`<div class="col-6 bg-deep-orange"><strong>col-6</strong><br> bg-deep-orange</div>`

**Comment by alexanderGugel** [comment]
Thanks. Will fix ASAP.

**Comment by alexanderGugel** [comment]
Fixed.
