### ISSUE TITLE
Use of multiple <main> tags is discouraged

### ISSUE THREAD

**Issue by RangerMauve** [alexanderGugel/papier#4]
It seems that this framework relies on using a `<main>` tag for the panel contents of all panels, this seems like incorrect behavior because of the way `<main>` tags are supposed to be used.

Per the [W3C spec](http://www.w3.org/html/wg/drafts/html/master/grouping-content.html#the-main-element) on the `<main>` element, it says to only use it once on the page.

Now, the [WHATWG spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element) Might be OK with having multiple `<main>` tags, but by the looks of it, most people are suggesting to use the W3C version.

Would you consider using something other than main? Or is there an alternative element that can already be used?

**Comment by alexanderGugel** [comment]
You are correct. Panels indeed depend on having a main element within them. That being said, I'm planning to make the semantic part entirely optional by adding corresponding classes.

This way, `<main>` would be equivalent to `<whatever class="main">`.

On the other hand,

``` html
          <section class="panel">
            <header class="bg-subtle">I am a header</header>
            <main>This is where the content goes...</main>
          </section>
```

is probably more convenient and readable than

``` html
          <section class="panel">
            <div class="header bg-subtle">I am a header</div>
            <div class="main">This is where the content goes...</div>
          </section>
```

I agree that we should be aiming for 100% compliance with the W3C spec, but for the time being, I think this solution works fine.

But if you want to take a shot at this, I'm more than happy to merge it in.

**Comment by RangerMauve** [comment]
From the looks of it, people are just using <p> tags to specify the content of a section, would that make sense to you as an alternative?
