### ISSUE TITLE
Easy stylus import

### ISSUE THREAD

**Issue by eyy** [alexanderGugel/papier#6]
Is there a way to easily `@import 'papier'` in stylus sheets like nib?
Thanks.

**Comment by alexanderGugel** [comment]
Yes! While it seems like making `@import 'papier'` work would require an `index.styl` file to be added, you can simply `npm install` and `@import` from `node_modules`.

**Comment by eyy** [comment]
But that requires a relative path from my stylesheet to the node_modules dir: `@import '../../node_modules/papier'`. What if the paths will change? Is there a way for a simple `@import 'papier'` which will resolve itself? I have no idea how it works for nib.

**Comment by alexanderGugel** [comment]
Yes, that's true. Adding an `index.styl` (equivalent to `index.js`) to papier would solve this problem. Feel free to send a PR if you like, otherwise I'm going to add this when I have time.
