### ISSUE TITLE
ISC or MIT license?

### ISSUE THREAD

**Issue by maruilian11** [alexanderGugel/papier#8]
hi, recently we want to add your lib on https://cdnjs.com, i saw MIT license on your repo but ISC in your [package.json](https://github.com/alexanderGugel/papier/blob/master/package.json#L13), just want to confirm this with you. 
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6865

**Comment by alexanderGugel** [comment]
Fine with either. Just submit a PR.

**Comment by maruilian11** [comment]
ok, thank you very much!
